# permissions for end users to edit ipxebootconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipxebootconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ipxe-operator
    app.kubernetes.io/part-of: ipxe-operator
    app.kubernetes.io/managed-by: kustomize
  name: ipxebootconfig-editor-role
rules:
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs/status
  verbs:
  - get
