---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - boot.ironcore.dev
  resources:
  - httpbootconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boot.ironcore.dev
  resources:
  - httpbootconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - boot.ironcore.dev
  resources:
  - httpbootconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfig
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfig/status
  verbs:
  - get
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - serverbootconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - serverbootconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - serverbootconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
