---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - boot.ironcore.dev
  resources:
  - ipxebootconfigs/status
  verbs:
  - get
  - patch
  - update
