apiVersion: boot.ironcore.dev/v1alpha1
kind: HTTPBootConfig
metadata:
  labels:
    app.kubernetes.io/name: httpbootconfig
    app.kubernetes.io/instance: httpbootconfig-sample
    app.kubernetes.io/part-of: boot-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: boot-operator
  name: httpbootconfig-sample
spec:
  ignitionSecretRef:
    name: ignition-foo
    namespace: default
  systemIPs:
  - f55b:9d4e:e9c9:5183:f7e8:3012:60ce:497b
  - 1001:194a:21fb:53d3:9de1:28f3:97ce:d31d
  systemUUID: abcd648-490f-11ea-a6c2-0a94efaabcdrd
  ukiURL: http://[feed:c0de::]/httpboot/foo-os-uki.efi