apiVersion: boot.ironcore.dev/v1alpha1
kind: HTTPBootConfig
metadata:
  labels:
    app.kubernetes.io/name: httpbootconfig
    app.kubernetes.io/instance: httpbootconfig-sample
    app.kubernetes.io/part-of: ipxe-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ipxe-operator
  name: httpbootconfig-sample
spec:
  systemUUID: 1234
  systemIPs:
    - 1.2.3.4
  ignitionSecretRef:
    name: ignition-sample
  ukiURL: http://1.2.3.4/uki.efi
  
