apiVersion: boot.ironcore.dev/v1alpha1
kind: IPXEBootConfig
metadata:
  labels:
    app.kubernetes.io/name: ipxebootconfig
    app.kubernetes.io/instance: ipxebootconfig-sample
    app.kubernetes.io/part-of: ipxe-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ipxe-operator
  name: ipxebootconfig-sample
spec:
  systemUUID: "1234"
  systemIP: "10.0.0.2" 
  ignitionSecretRef:
    name: ignition-sample
  image: gardenlinux:latest
  kernelURL: "10.0.0.1/ipxe/rootfs.vmlinuz"
  initrdURL: "10.0.0.1/ipxe/rootfs.initrd"
  squashfsURL: "10.0.0.1/ipxe/root.squashfs"